server:
  port: 8090
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

management:
  endpoint:
    health.enabled: true
    metrics.enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure.include: "health,metrics"
      base-path: /
    jmx.exposure.exclude: "*"
  metrics:
    enable.jvm: true
  server:
    port: 5556

acquiring:
  bank:
    host: http://localhost:8080